# These are supported funding model platforms

github: [Stonesalltheway1]
patreon: # Replace with a Patreon username
open_collective: # Replace with an Open Collective username
ko_fi: # Replace with a Ko-fi username
tidelift: # Replace with a Tidelift platform-name/package-name
community_bridge: # Replace with a Community Bridge project-name
liberapay: # Replace with a Liberapay username
issuehunt: # Replace with an IssueHunt username
otechie: # Replace with an Otechie username
custom: ['https://gumroad.com/fileflow']
