name: FileFlow Development
description: Project board for tracking FileFlow development and releases

columns:
  - name: To Do
    description: Tasks that need to be completed
    initial: true
    
  - name: In Progress
    description: Tasks currently being worked on
    
  - name: Review
    description: Tasks pending review or testing
    
  - name: Done
    description: Tasks that have been completed

labels:
  - name: bug
    color: '#d73a4a'
    description: Something isn't working
    
  - name: enhancement
    color: '#a2eeef'
    description: New feature or request
    
  - name: documentation
    color: '#0075ca'
    description: Improvements or additions to documentation
    
  - name: licensing
    color: '#e4e669'
    description: Related to the licensing system
    
  - name: premium-feature
    color: '#7057ff'
    description: Premium or Business tier features
